name: Playwright test
on: [deployment_status]
jobs:
  run_e2e_test:
    name: Run E2E test with Playwright
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: microsoft/playwright-github-action@v1
      - run: yarn
      - run: npx playwright install
      - run: yarn test:e2e
        env:
          TARGET_URL: ${{github.event.deployment_status.target_url}}
